### ISSUE TITLE
Validation does not work because of photo_url in initData (I guess)

### ISSUE THREAD

**Issue by zytfo** [nimaxin/init-data-py#6] opened 2024-11-12 19:03 UTC
Now Telegram sends photo_url within an initData, validate method stopped working

**Comment by nimaxin** [comment] 2024-11-13 09:38
Yes, you're right. The issue is due to the addition of `photo_url` and its backslashes not being parsed correctly. This means that any presence of backslashes in `init_data` prevents the library from functioning as expected. Currently, I don’t have a fix for this issue, and the solution I have in mind would require releasing a new major version (v1) of the library to prevent similar bugs in the future. The idea would be to validate init_data directly without parsing, just as Telegram’s website suggests.

For now, I recommend using this method to validate init_data until I can release an updated version. However, due to time constraints, I don't know when I will be able to make these changes.
```python
def validate_init_data(init_data: str, bot_token: str):
    vals = {k: unquote(v) for k, v in [s.split('=', 1) for s in init_data.split('&')]}
    data_check_string = '\n'.join(f"{k}={v}" for k, v in sorted(vals.items()) if k != 'hash')

    secret_key = hmac.new("WebAppData".encode(), bot_token.encode(), hashlib.sha256).digest()
    h = hmac.new(secret_key, data_check_string.encode(), hashlib.sha256)
    return h.hexdigest() == vals['hash']
# https://stackoverflow.com/a/78441046/17861015
```
If you or anyone else is able to resolve this issue, a PR would be greatly appreciated.

**Comment by Slava191** [comment] 2024-11-13 10:33
Hello. Need fix.

**Comment by swer4ock** [comment] 2024-11-13 16:18
Has anyone been able to find a solution?

**Comment by Slava191** [comment] 2024-11-13 16:24
> Has anyone been able to find a solution?

I've temporarily used the method that was suggested by the package author (@nimaxin) in this topic instead of validate method from the package. It works well.

But I'm still waiting for an update in the package. I hope it will happen soon)

We need a hero who will suggest PR with improvements 🦸‍♂️

**Closed as completed** 2024-11-15 22:23 UTC
Labels: bug
